server:
  port: 8080

spring:
  cloud:
    gateway:
      server:
        webflux:
          globalcors:
            cors-configurations:
              '[/**]':
                allowed-origins:
                  - "http://localhost:4200"
                allowed-methods:
                  - GET
                  - POST
                  - PUT
                  - DELETE
                  - PATCH
                  - OPTIONS
                allowed-headers:
                  - "*"
                allow-credentials: true

          routes:
            - id: user-auth-route
              uri: lb://USER-SERVICE
              predicates:
                - Path=/auth/**

            - id: user-route
              uri: lb://USER-SERVICE
              predicates:
                - Path=/users/**

            - id: role-route
              uri: lb://ROLE-SERVICE
              predicates:
                - Path=/roles/**

            - id: manager-route
              uri: lb://USER-SERVICE
              predicates:
                - Path=/manager/**

            - id: admin-route
              uri: lb://USER-SERVICE
              predicates:
                - Path=/admin/**

            - id: product-route
              uri: lb://PRODUCT-SERVICE
              predicates:
                - Path=/product/**

            - id: order-route
              uri: lb://ORDER-SERVICE
              predicates:
                - Path=/orders/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION:3600000}

management:
  endpoint:
    gateway:
      access: read-only
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - metrics
          - gateway