#PATCH http://localhost:8080/orders/56/cancel
#Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbkBnbWFpbC5jb20iLCJ1c2VySWQiOjEsImVtYWlsIjoiYWRtaW5AZ21haWwuY29tIiwicm9sZXMiOlsiQURNSU4iXSwiaWF0IjoxNzg5MTMwNDYxLCJleHAiOjE3ODkxMzQwNjF9.0Xu_NLgunbB6y3fk18MzXOm10TfTENRj8U8JzeglxHs8YMoClOMM_cf-RxCTohuZMDpRP7iAqSf40ThAoqSn5g
POST http://localhost:8080/orders
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJuYXNpcmJoYWtzaGV5NDRAZ21haWwuY29tIiwidXNlcklkIjo0LCJlbWFpbCI6Im5hc2lyYmhha3NoZXk0NEBnbWFpbC5jb20iLCJyb2xlcyI6WyJVU0VSIl0sImlhdCI6MTc4OTEzMDM3NiwiZXhwIjoxNzg5MTMzOTc2fQ.vNRJ6BrtU-wcGQiKopi46EGfFPhLeIDN-8ns5gfILap3gB-OoBvmONkcdom_4wZg2w0AoxdWgz-E09k4W0CknA
Content-Type: application/json

{
  "items": [
    {
      "productId": 2,
      "quantity": 2
    }
  ]
}
