POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "email": "nasirbhakshey44@gmail.com",
  "password": "nasir@1234"
}
#Content-Type: application/json
#
#{
#  "email": "nasirbhakshey44@gmail.com",
#  "password": "nasir@1234"
#}

#GET http://localhost:8080/users/profile
#Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJtYW5hZ2VyQGdtYWlsLmNvbSIsInVzZXJJZCI6MywiZW1haWwiOiJtYW5hZ2VyQGdtYWlsLmNvbSIsInJvbGVzIjpbIk1BTkFHRVIiXSwiaWF0IjoxNzg3Mzk4ODQ5LCJleHAiOjE3ODc0MDI0NDl9.07bhjv9SKM5kqprwLyceDHpIyrPmCHSiNgXRh4Uv6nc5XeHhcepcaHaCDaQol4FDqPipnpDfn88P-loPpd6Icw
