CREATE TABLE processed_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    consumer_name VARCHAR(150) NOT NULL,
    event_id UUID NOT NULL,
    event_type VARCHAR(100) NOT NULL,
    processed_at TIMESTAMP(6) NOT NULL,

    CONSTRAINT uk_processed_event_consumer
        UNIQUE (event_id, consumer_name)
);

CREATE INDEX idx_processed_event_id
    ON processed_events (event_id);
