CREATE TABLE orders (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        created_at TIMESTAMP(6) NOT NULL,
                        status VARCHAR(255) NOT NULL,
                        total_amount NUMERIC(12,2) NOT NULL,
                        user_id BIGINT NOT NULL
);

CREATE TABLE order_items (
                             id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             price NUMERIC(12,2) NOT NULL,
                             product_id BIGINT NOT NULL,
                             quantity INTEGER NOT NULL,
                             order_id BIGINT NOT NULL,

                             CONSTRAINT fkbioxgbv59vetrxe0ejfubep1w
                                 FOREIGN KEY (order_id)
                                     REFERENCES orders(id)
);

CREATE TABLE outbox_events (
                               id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               aggregate_id VARCHAR(255) NOT NULL,
                               aggregate_type VARCHAR(255) NOT NULL,
                               created_at TIMESTAMP(6) NOT NULL,
                               event_type VARCHAR(255) NOT NULL,
                               payload TEXT NOT NULL,
                               published BOOLEAN NOT NULL,
                               published_at TIMESTAMP(6),
                               topic VARCHAR(255) NOT NULL
);

CREATE TABLE processed_events (
                                  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                  consumer_name VARCHAR(150) NOT NULL,
                                  event_id UUID NOT NULL,
                                  event_type VARCHAR(100) NOT NULL,
                                  processed_at TIMESTAMP(6) NOT NULL,

                                  CONSTRAINT uk_processed_event_consumer
                                      UNIQUE (event_id, consumer_name)
);

CREATE INDEX idx_processed_event_id
    ON processed_events (event_id);