CREATE TABLE payments (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          amount NUMERIC(12,2) NOT NULL,
                          created_at TIMESTAMP(6) NOT NULL,
                          order_id BIGINT NOT NULL,
                          status VARCHAR(255) NOT NULL,
                          transaction_id VARCHAR(255),
                          updated_at TIMESTAMP(6),
                          user_id BIGINT NOT NULL,

                          CONSTRAINT uk_payment_order
                              UNIQUE (order_id),

                          CONSTRAINT uklryndveuwa4k5qthti0pkmtlx
                              UNIQUE (transaction_id),

                          CONSTRAINT payments_status_check
                              CHECK (status IN ('PENDING', 'SUCCESS', 'FAILED', 'REFUNDED'))
);

CREATE TABLE outbox_events (
                               id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               aggregate_id VARCHAR(255) NOT NULL,
                               aggregate_type VARCHAR(255) NOT NULL,
                               created_at TIMESTAMP(6) NOT NULL,
                               event_type VARCHAR(255) NOT NULL,
                               payload TEXT NOT NULL,
                               published BOOLEAN NOT NULL,
                               published_at TIMESTAMP(6),
                               topic VARCHAR(255) NOT NULL
);

CREATE INDEX idx_payment_outbox_published_created
    ON outbox_events (published, created_at);

CREATE TABLE processed_events (
                                  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                  consumer_name VARCHAR(150) NOT NULL,
                                  event_id UUID NOT NULL,
                                  event_type VARCHAR(100) NOT NULL,
                                  processed_at TIMESTAMP(6) NOT NULL,

                                  CONSTRAINT uk_processed_event_consumer
                                      UNIQUE (event_id, consumer_name)
);

CREATE INDEX idx_processed_event_id
    ON processed_events (event_id);