spring:
  application:
    name: user-service

  config:
    import:
      - optional:configserver:http://localhost:8888


#jwt:
#  secret: ${JWT_SECRET:change-this-to-a-very-long-secret-key-for-local-development-only}
#  expiration: ${JWT_EXPIRATION:3600000}