CREATE TABLE products (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          description VARCHAR(255),
                          name VARCHAR(255),
                          price NUMERIC(38,2),
                          stock INTEGER
);

CREATE TABLE inventory_reservations (
                                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                        order_id BIGINT NOT NULL,
                                        product_id BIGINT NOT NULL,
                                        quantity INTEGER NOT NULL,
                                        status VARCHAR(255) NOT NULL,

                                        CONSTRAINT uk_inventory_reservation_order_product
                                            UNIQUE (order_id, product_id),

                                        CONSTRAINT inventory_reservations_status_check
                                            CHECK (status IN ('RESERVED', 'COMMITTED', 'RESTORED', 'CANCELLED'))
);

CREATE TABLE outbox_events (
                               id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               aggregate_id VARCHAR(255) NOT NULL,
                               aggregate_type VARCHAR(255) NOT NULL,
                               created_at TIMESTAMP(6) NOT NULL,
                               event_type VARCHAR(255) NOT NULL,
                               payload TEXT NOT NULL,
                               published BOOLEAN NOT NULL,
                               published_at TIMESTAMP(6),
                               topic VARCHAR(255) NOT NULL
);

CREATE INDEX idx_outbox_published_created
    ON outbox_events (published, created_at);

CREATE TABLE processed_events (
                                  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                  consumer_name VARCHAR(150) NOT NULL,
                                  event_id UUID NOT NULL,
                                  event_type VARCHAR(100) NOT NULL,
                                  processed_at TIMESTAMP(6) NOT NULL,

                                  CONSTRAINT uk_processed_event_consumer
                                      UNIQUE (event_id, consumer_name)
);

CREATE TABLE processed_inventory_events (
                                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                            order_id BIGINT NOT NULL,
                                            processed_at TIMESTAMP(6) NOT NULL,

                                            CONSTRAINT uk_processed_inventory_order
                                                UNIQUE (order_id)
);